# Generated by Django 3.0.5 on 2020-04-27 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200423_1713'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
